[package]
name = "tokenizers_jni"
version = "0.1.0"
edition = "2021"

[lib]
name = "tokenizersjni"
path = "src/lib.rs"
bench = false
crate-type = ["staticlib", "dylib"]

[dependencies]
tokenizers = "0.19.1"
log = "0.4"
jni = { version = "0.5", default-features = false }
android_logger = "0.13"
